# composing Docker development environment

version: '3.8'

services:
  db:
    build: docker/localized_postgres/.
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  # Use this service to simulate running the release image on this development system.
  # To make sure PORT configurations are in place, it is not running on port 4000.
  staging:
    image: docker.thorsten-michael.de/tmde:staging
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/tmde_dev
      - SECRET_KEY_BASE=PtApWjeuuk6XNDIxpNc9HBQRKowJv/LOgkNjR9z2rxiIvwm3+FDzSNtypGe1/+tq
      - PORT=8080
    depends_on:
      - db

  adminer:
    image: adminer
    links:
      - db:db
    ports:
      - 4004:8080

volumes:
  db_data:


